version: "3.9"

services:
  app:
    build: .
    container_name: 'proger_trainer'
    ports:
      - "8084:8080"
    depends_on:
      - db
    environment:
      POSTGRES_URL: "jdbc:postgresql://db:5432/proger_trainer"
      POSTGRES_USERNAME: "developer"
      POSTGRES_PASSWORD: "developer"
    networks:
      - backend

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=proger_trainer
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U developer -d proger_trainer" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - backend

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    volumes:
#      - grafana-storage:/var/lib/grafana
#
#volumes:
#  grafana-storage:

networks:
  backend:
    driver: bridge