spring:
  application:
    name: progerTrainer
  datasource:
    username: ${POSTGRES_USERNAME:postgrtes}
    password: ${POSTGRES_PASSWORD:postgrtes}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/proger_trainer}
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/proger_trainer}
    user: ${POSTGRES_USERNAME:postgrtes}
    password: ${POSTGRES_PASSWORD:postgrtes}
    default-schema: proger_trainer
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

db:
  schema: proger_trainer