spring:
  application:
    name: progerTrainer
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: ${POSTGRES_URL}
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    default-schema: proger_trainer
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true

db:
  schema: proger_trainer