spring:
  application:
    name: progerTrainer

  config:
    import: application-db.yml, 
            application-kafka.yml, 
            application-logging.yml,
            application-monitoring.yml,
            application-security.yml